- name: SDDM configuration
  ansible.builtin.file:
    path: "/etc/sddm.conf.d/{{ item }}"
    state: absent
  loop:
    - "10-wayland.conf"
    - "dpi.conf"
    - "theme.conf"

- name: Paru config
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/paru"
    state: absent

- name: Sway config
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/sway"
    state: absent
