- name: SDDM configuration
  ansible.builtin.file:
    path: "/etc/sddm.conf.d/{{ item }}"
    state: absent
  loop:
    - "10-wayland.conf"
    - "dpi.conf"
    - "theme.conf"

- name: Paru config
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/paru"
    state: absent

- name: Sway config
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/sway"
    state: absent

- name: Systemd units
  ansible.builtin.copy:
    path: "~/.config/systemd/user/{{ item.path }}"
    state: absent
  with_community.general.filetree: "{{ 'systemd/' }}"

- name: Kanshi config
  ansible.builtin.file:
    path: "~/.config/kanshi"
    state: absent

- name: Global environment variables
  ansible.builtin.file:
    path: "~/.pam_environment"
    state: absent

- name: Remove shell snippets
  ansible.builtin.file:
    path: "~/.sh.d/{{ item }}"
    state: absent
  loop: []
