- name: SDDM configs
  become: true
  ansible.builtin.copy:
    src: "sddm/{{ item }}"
    dest: "/etc/sddm.conf.d/{{ item }}"
    owner: 0
    group: 0
    mode: u=rw,go=r
  loop:
    - "10-wayland.conf"
    - "dpi.conf"
    - "theme.conf"

- name: Paru config
  ansible.builtin.copy:
    src: "paru"
    dest: "~/.config/"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: u=rw,go=r
    directory_mode: u=rwx,go=rx

- name: Sway config
  ansible.builtin.copy:
    src: "sway"
    dest: "~/.config/"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: u=rw,go=r
    directory_mode: u=rwx,go=rx

- name: Systemd units
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "~/.config/systemd/user/{{ item.path }}"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: u=rw,go=r
  with_community.general.filetree: "{{ 'systemd/' }}"

- name: Reload user Systemd
  ansible.builtin.systemd:
    scope: user
    daemon_reload: true

- name: Systemd user service
  ansible.builtin.systemd:
    scope: user
    name: "{{ item.path }}"
    enabled: true
  ignore_errors: "{{ ansible_check_mode }}"
  with_community.general.filetree: "{{ 'systemd/' }}"
  when: item.path | splitext | last == ".service"

- name: Kanshi config
  ansible.builtin.copy:
    src: "kanshi"
    dest: "~/.config/"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: u=rw,go=r
    directory_mode: u=rwx,go=rx

- name: Global environment variables
  ansible.builtin.copy:
    src: "pam_environment"
    dest: "~/.pam_environment"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: u=rw,go=r
    directory_mode: u=rwx,go=rx

- name: Add shell snippets
  ansible.builtin.copy:
    src: "shell-snippets/{{ item }}"
    dest: "~/.sh.d/{{ item }}"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: u=rwx,go=rx
  loop:
    - "50-fixwifi.sh"
