---
# Plugin: fzf
- name: Add/Remove fzf plugin dependency
  when: "'fzf' in oh_my_zsh_plugins or state == 'absent'"
  become: "{{ ansible_distribution != 'MacOSX' }}"
  ansible.builtin.package:
    name: fzf
