" https://github.com/junegunn/vim-plug
call plug#begin('~/.vim/plugged')

Plug 'frazrepo/vim-rainbow'
Plug 'hashivim/vim-terraform'
Plug 'airblade/vim-gitgutter'
Plug 'neovim/nvim-lspconfig'
Plug 'simrat39/rust-tools.nvim'

call plug#end()

" Hybrid numbers for active buffer
" https://jeffkreeftmeijer.com/vim-number/
:set number

:augroup numbertoggle
:  autocmd!
:  autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu && mode() != "i" | set rnu   | endif
:  autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu                  | set nornu | endif
:augroup END

" Display
set ruler
set scrolloff=5
set wrap
colorscheme slate

" Editing
set autoindent
set expandtab
set shiftwidth=4
set tabstop=4
syntax on
set confirm

noremap ; l
noremap j k
noremap k j
noremap j h

" Search
set hlsearch
set incsearch
set smartcase

" Highlight trailing whitespace
highlight RedundantSpaces ctermbg=red guibg=red
match RedundantSpaces /\s\+$/

" Save with sudo
cnoremap w!! w !sudo tee > /dev/null %
