---
- name: Remove shell snippets
  ansible.builtin.file:
    path: "~/.sh.d/{{ item }}"
    state: absent
  loop:
    - "50-alias.sh"
    - "50-cargo-bins.sh"
    - "50-clipboard.sh"
    - "50-misc.sh"
    - "50-mkcd.sh"
    - "50-utime.sh"
