---
- name: Ensure state
  ansible.builtin.include_tasks:
    file: "{{ state }}.yml"

- name: Install/Remove packages
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - sipcalc
    - htop
    - glances
    - ncdu
    - bc
