---
- name: Shell script snippet directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.sh.d"
    state: "{% if state == 'present' %}directory{% else %}{{ state }}{% endif %}"
    mode: u=rwx,go=rx
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"

- name: Ensure state
  ansible.builtin.include_tasks:
    file: "{{ state }}.yml"

- name: Install/Remove packages
  become: "{{ ansible_distribution != 'MacOSX' }}"
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - sipcalc
    - htop
    - glances
    - ncdu
    - bc
    - jq
    - yq
    - ripgrep
