---
- name: Setup desktop
  hosts: localhost
  gather_facts: true
  become: false
  vars_prompt:
    - name: state
      prompt: Install or uninstall (absent; present)
      default: present
      private: false
      confirm: "{{ not ansible_check_mode }}"
  roles:
    - role: "jenrik.setup.common"
    - role: "jenrik.setup.zsh"
      vars:
        minimal: false
        oh_my_zsh_plugins:
          - git
          - fzf
          - bgnotify
    - role: "jenrik.setup.git"
    - role: "jenrik.setup.vim"
    - role: "jenrik.setup.archlinux"
      when: ansible_distribution == "Archlinux"
  tasks:
    - name: Create project directory
      ansible.builtin.file:
        path: "{{ ansible_env.XDG_HOME | default(ansible_env.HOME) }}/projects"
        state: "{% if state == 'present' %}directory{% else %}{{ state }}{% endif %}"
        owner: "{{ ansible_user_uid }}"
        group: "{{ ansible_user_gid }}"
        mode: u=rwx,go=rx
